name: "personal-details"
version: "1.0"
modelUrl: "https://github.com/mghaigh/personal-details/blob/master/personal-details.xml"
imagesDir: "images"
dtoModelFileType: "json"
outputDir: "generated"
modelConfig:
  typesPackageName: "Types"
  defaults:
    classActions:
      - CREATE
      - READ
dependencies:
  - modelUrl: "https://github.com/mghaigh/core-types/blob/master/generated/mtt-models/core-types.json"
#  - modelUrl: "file:///C:/Users/martin/Projects/models/personal-details/uml-model/personal-details-dto.json"
    version: "1.0.0"
loader:
  name: "eaxmiloader"
  configUrl: "https://github.com/mghaigh/personal-details/blob/master/config/loaders/ea-xmi/application.yaml"
  outputFolder: "mtt-models"
#    configUrl: "file:///C:/Users/martin/Projects/models/personal-details/config/generators/openapi/config.yaml"
generators:
  aoco:
    configUrl: "https://github.com/mghaigh/personal-details/blob/master/config/generators/aoco/aoco.yaml"
    outputFolder: "specs/aoco"
  oml:
    configUrl: "https://github.com/mghaigh/personal-details/blob/master/config/generators/oml/oml.yaml"
    outputFolder: "specs/oml"




