modelFileUrl: "https://github.com/mghaigh/personal-details/blob/master/personal-details.xml"
outputDirUrl: "https://github.com/mghaigh/personal-details/tree/master/generated/"
modelConfig:
  packageNames:
    typesPackage: "Personal Details"
dependencies:
  "Core Types":
    modelFileUrl: "https://github.com/mghaigh/core-types/blob/master/generated/mtt-models/core-types.json"
    version: "1.0.0"
loader:
  generatorUrl: "http://localhost:8005"
  configFileUrl: "https://github.com/mghaigh/common-config/blob/master/config/loaders/ea-xmi/config.yaml"
generators:
  # mkdocs:
  - generatorUrl: "http://localhost:9020"
    configFileUrl: "https://github.com/mghaigh/common-config/blob/master/config/generators/mkdoc/config.yaml"



