modelFileURI: "https://github.com/mghaigh/personal-details/blob/master/personal-details.xml"
outputDirURI: "https://github.com/mghaigh/personal-details/tree/master/generated/"
modelConfig:
  packageNames:
    typesPackage: "Personal Details"
dependencies:
  "Core Types":
    modelFileURI: "https://github.com/mghaigh/core-types/blob/master/generated/mtt-models/core-types.json"
    version: "1.0.0"
loader:
  loaderURL: "http://localhost:7010"
  configFileURI: "https://github.com/mghaigh/common-config/blob/master/config/loaders/ea-xmi/config.yaml"
generators:
  # mkdocs:
  - generatorURL: "http://localhost:9020"
    configFileURI: "https://github.com/mghaigh/common-config/blob/master/config/generators/mkdoc/config.yaml"



