# iri: "<http://example.com/tutorial1/vocabulary/pizza#> as pizza"
typeMap:
  "Boolean": "xsd:boolean"
  "DateTime": "xsd:datetime"
  "Float": "xsd:decimal"
  "Int": "xsd:integer"
  "String": "xsd:string"
